### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by jamietanna** [yayolande/go-template-lsp#1]
Thanks for this very awesome project 👀

In case you're unaware, the lack of a license on the project means it'll default to All-Rights-Reserved, aka proprietary, so no one can contribute

**Comment by yayolande** [comment]
Thanks a lot, I wasn't aware of such thing.

The matter have been resolved, I added an **MIT** license to the project.
Again, thank you for the feedback.

**Comment by jamietanna** [comment]
Thank you!

It's something that's not commonly known and one of my most raised issues with new projects I come across 😁
